services:
  avahi:
    image: flungo/avahi
    container_name: avahi
    restart: unless-stopped
    network_mode: host
    environment:
      - SERVER_HOST_NAME=grom
      # Found this using the `ip a` command
      - SERVER_ALLOW_INTERFACES=eno1,br-9d1df798fdaf
      - REFLECTOR_ENABLE_REFLECTOR=yes
    volumes:
      - /run/dbus:/run/dbus