services:
  avahi:
    image: flungo/avahi
    container_name: avahi
    restart: unless-stopped
    network_mode: host
    environment:
      SERVER_HOST_NAME: grom
      REFLECTOR_ENABLE_REFLECTOR: yes
    volumes:
      - /run/dbus:/run/dbus
