services:
  minecraft-server:
    image: itzg/minecraft-server:2024.5.0
    container_name: minecraft-server
    restart: unless-stopped
    tty: true
    stdin_open: true
    environment:
      DEBUG: true
      EULA: true
      TYPE: PURPUR
      USE_SIMD_FLAGS: true
      VERSION: 1.20.6
      DIFFICULTY: normal
      MOTD: "she's gracked"
      CF_API_KEY: ${CF_API_KEY}
      CURSEFORGE_FILES: |
        https://www.curseforge.com/minecraft/bukkit-plugins/dead-chest
        https://www.curseforge.com/minecraft/bukkit-plugins/dropheads
        https://www.curseforge.com/minecraft/bukkit-plugins/spawnersilk
        https://www.curseforge.com/minecraft/bukkit-plugins/thizzyz-tree-feller
      OPS: |
        beanjuicevrrrm
    networks:
      - traefik_default
    volumes:
      - data:/data

  router:
    image: itzg/mc-router:1.20.3
    container_name: minecraft-router
    restart: unless-stopped
    depends_on:
      - minecraft-server
    environment:
      MAPPING: |
        iluvgrack.local.alexisthe.best=minecraft-server:25565
    labels:
      traefik.enable: true
      traefik.tcp.routers.minecraft-router.entrypoints: minecraft
      traefik.tcp.routers.minecraft-router.rule: HostSNI(`*`)
      traefik.tcp.services.minecraft-router.loadbalancer.server.port: 25565
    networks:
      - traefik_default

volumes:
  data:

networks:
  traefik_default:
    external: true