services:
  traefik:
    image: traefik:v2.11
    restart: unless-stopped
    container_name: traefik
    environment:
      - CF_DNS_API_TOKEN=${CF_DNS_API_TOKEN}
    command: |
      --api=true
      --log.level=DEBUG

      --providers.docker=true
      --providers.docker.exposedByDefault=false

      --entryPoints.dnstcp.address=:53/tcp
      --entryPoints.dnsudp.address=:53/udp
      --entryPoints.web.address=:80
      --entryPoints.websecure.address=:443
      --entryPoints.homekit.address=:21063
      --entryPoints.minecraft.address=:25565

      --entryPoints.web.http.redirections.entryPoint.to=websecure
      --entryPoints.web.http.redirections.entryPoint.scheme=https

      --certificatesresolvers.cloudflare.acme.email=alexjmcd2202@gmail.com
      --certificatesresolvers.cloudflare.acme.storage=/ssl-certs/acme.json
      --certificatesresolvers.cloudflare.acme.caserver=https://acme-v02.api.letsencrypt.org/directory
      --certificatesresolvers.cloudflare.acme.dnschallenge=true
      --certificatesresolvers.cloudflare.acme.dnschallenge.provider=cloudflare
      --certificatesresolvers.cloudflare.acme.dnschallenge.resolvers=1.1.1.1:53,1.0.0.1:53
    labels:
      traefik.enable: true
      traefik.http.routers.traefik.tls.certresolver: cloudflare
      traefik.http.routers.traefik.entrypoints: websecure
      traefik.http.routers.traefik.rule: Host(`traefik.local.alexisthe.best`)
      traefik.http.routers.traefik.service: api@internal
      traefik.http.routers.traefik.tls.domains[0].main: local.alexisthe.best
      traefik.http.routers.traefik.tls.domains[0].sans: "*.local.alexisthe.best"
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "80:80"
      - "443:443"
      - "21063:21063"
      - "25565:25565"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ssl-certs:/ssl-certs

  whoami:
    image: traefik/whoami:v1.10
    container_name: whoami
    restart: unless-stopped
    labels:
      traefik.enable: true
      traefik.http.routers.whoami.tls.certresolver: cloudflare
      traefik.http.routers.whoami.entrypoints: websecure
      traefik.http.routers.whoami.rule: Host(`whoami.local.alexisthe.best`)

volumes:
  ssl-certs:
