services:
  traefik:
    image: traefik:v2.11
    restart: unless-stopped
    container_name: traefik
    environment:
      - CF_DNS_API_TOKEN=$CF_DNS_API_TOKEN
    command: |
      --api=true

      --providers.docker
      --providers.docker.exposedByDefault=false

      --entryPoints.dns.address=:53/udp
      --entryPoints.web.address=:80
      --entryPoints.websecure.address=:443

      --entryPoints.web.http.redirections.entryPoint.to=websecure
      --entryPoints.web.http.redirections.entryPoint.scheme=https

      --certificatesresolvers.staging.acme.dnschallenge=true
      --certificatesresolvers.staging.acme.dnschallenge.provider=cloudflare
      --certificatesresolvers.staging.acme.email=alexjmcd2202@gmail.com
      --certificatesresolvers.staging.acme.storage=/ssl-certs/acme.json
      --certificatesresolvers.staging.acme.caserver=https://acme-staging-v02.api.letsencrypt.org/directory

      --certificatesresolvers.production.acme.dnschallenge=true
      --certificatesresolvers.production.acme.dnschallenge.provider=cloudflare
      --certificatesresolvers.production.acme.email=alexjmcd2202@gmail.com
      --certificatesresolvers.production.acme.storage=/ssl-certs/acme.json
      --certificatesresolvers.production.acme.caserver=https://acme-v02.api.letsencrypt.org/directory
    labels:
      traefik.enable: true
      traefik.http.routers.traefik.tls: true
      traefik.http.routers.traefik.tls.certresolver: staging
      traefik.http.routers.traefik.entrypoints: websecure
      traefik.http.routers.traefik.rule: Host(`traefik.local.alexisthe.best`)
      traefik.http.routers.traefik.service: api@internal

      # Wildcard certificates
      traefik.http.routers.traefik.tls.domains[0].main: alexisthe.best
      traefik.http.routers.traefik.tls.domains[0].sans[0]: "*.alexisthe.best"
      traefik.http.routers.traefik.tls.domains[0].sans[1]: "*.local.alexisthe.best"
    ports:
      - "53:53/udp"
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ssl-certs:/ssl-certs

volumes:
  ssl-certs:
