services:
  traefik:
    image: traefik:v2.11
    restart: unless-stopped
    container_name: traefik
    environment:
      - CF_DNS_API_TOKEN=$CF_DNS_API_TOKEN
    command: |
      --api=true
      --log.level=DEBUG

      --providers.docker
      --providers.docker.exposedByDefault=false

      --entryPoints.dns.address=:53/udp
      --entryPoints.web.address=:80
      --entryPoints.websecure.address=:443

      --entryPoints.web.http.redirections.entryPoint.to=websecure
      --entryPoints.web.http.redirections.entryPoint.scheme=https

      --certificatesresolvers.cloudflare.acme.email=alexjmcd2202@gmail.com
      --certificatesresolvers.cloudflare.acme.storage=/ssl-certs/acme.json
      --certificatesresolvers.cloudflare.acme.caserver=https://acme-staging-v02.api.letsencrypt.org/directory
      --certificatesresolvers.cloudflare.acme.dnschallenge=true
      --certificatesresolvers.cloudflare.acme.dnschallenge.provider=cloudflare
      --certificatesresolvers.cloudflare.acme.dnschallenge.resolvers=1.1.1.1:53,1.0.0.1:53
    labels:
      traefik.enable: true
      traefik.http.routers.traefik.tls: true
      traefik.http.routers.traefik.tls.certresolver: cloudflare
      traefik.http.routers.traefik.entrypoints: websecure
      traefik.http.routers.traefik.rule: Host(`traefik.local.alexisthe.best`)
      traefik.http.routers.traefik.service: api@internal
      traefik.http.middlewares.test-auth.basicauth.users: test:5f4dcc3b5aa765d61d8327deb882cf99
      traefik.http.routers.traefik.middlewares: test-auth@docker

      # Wildcard certificates
      traefik.http.routers.traefik.tls.domains[0].main: local.alexisthe.best
      traefik.http.routers.traefik.tls.domains[0].sans: "*.local.alexisthe.best"
    ports:
      - "53:53/udp"
      - "80:80"
      - "443:443"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ssl-certs:/ssl-certs

volumes:
  ssl-certs:
