default_config:


automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

http:
  use_x_forwarded_for: true
  trusted_proxies:
    - 192.168.50.0/24
    - 172.17.0.0/16

homekit:
  name: HomeKit Bridge
  advertise_ip: 192.168.50.22
