services:
  # avahi:
  #   image: flungo/avahi
  #   container_name: avahi
  #   restart: unless-stopped
  #   network_mode: host
  #   environment:
  #     - SERVER_USE_IPV4=yes
  #     - SERVER_ALLOW_INTERFACES=eno1
  #       WIDE_AREA_ENABLE_WIDE_AREA=yes
  #     - REFLECTOR_ENABLE_REFLECTOR=yes
  home-assistant:
    image: ghcr.io/home-assistant/home-assistant:2024.4.2
    container_name: home-assistant
    restart: unless-stopped
    volumes:
      - config:/config
      - /etc/localtime:/etc/localtime:ro
      - /run/dbus:/run/dbus:ro
    privileged: true
    network_mode: host
    # networks:
    #   - traefik_default
    # ports:
    #   - "21063:21063"
    #   - "21064:21064"
    #   - "8123:8123"
    #   - "40000:40000"
      # - "5353:5353/udp"

volumes:
  config:

networks:
  traefik_default:
    external: true



# tcp        0      0 0.0.0.0:21064           0.0.0.0:*               LISTEN      67/python3          
# tcp        0      0 0.0.0.0:21063           0.0.0.0:*               LISTEN      67/python3          
# tcp        0      0 192.168.50.22:35113     0.0.0.0:*               LISTEN      67/python3          
# tcp        0      0 0.0.0.0:8123            0.0.0.0:*               LISTEN      67/python3          
# tcp        0      0 192.168.50.22:40000     0.0.0.0:*               LISTEN      67/python3          


# udp        0      0 0.0.0.0:37326           0.0.0.0:*                           67/python3          
# udp        0      0 0.0.0.0:33989           0.0.0.0:*                           67/python3          
# udp        0      0 192.168.50.22:5353      0.0.0.0:*                           67/python3          
# udp        0      0 0.0.0.0:1900            0.0.0.0:*                           67/python3          
# udp        0      0 0.0.0.0:1900            0.0.0.0:*                           67/python3          
# udp        0      0 0.0.0.0:60850           0.0.0.0:*                           67/python3          
