services:
  avahi:
    image: flungo/avahi
    container_name: avahi
    restart: unless-stopped
    network_mode: host
    environment:
      - SERVER_HOST_NAME=grom
      - SERVER_ALLOW_INTERFACES=eno1,br-9d1df798fdaf
      - REFLECTOR_ENABLE_REFLECTOR=yes
    volumes:
      - /run/dbus:/run/dbus

  home-assistant:
    image: ghcr.io/home-assistant/home-assistant:2024.4.2
    container_name: home-assistant
    restart: unless-stopped
    volumes:
      - config:/config
      - /etc/localtime:/etc/localtime:ro
      - /run/dbus:/run/dbus
    privileged: true
    networks:
      - traefik_default
    labels:
      traefik.enable: true

      traefik.tcp.routers.home-assistant.entrypoints: homekit
      traefik.tcp.routers.home-assistant.rule: HostSNI(`*`)
      traefik.tcp.services.home-assistant.loadbalancer.server.port: 21063

      traefik.http.routers.home-assistant.tls: true
      traefik.http.routers.home-assistant.tls.certresolver: cloudflare
      traefik.http.routers.home-assistant.entrypoints: websecure
      traefik.http.routers.home-assistant.rule: Host(`home-assistant.local.alexisthe.best`)
      traefik.http.routers.home-assistant.service: home-assistant
      traefik.http.services.home-assistant.loadbalancer.server.port: 8123

volumes:
  config:

networks:
  traefik_default:
    external: true
