services:
  avahi:
    image: flungo/avahi
    container_name: avahi
    restart: unless-stopped
    network_mode: host
    environment:
      - SERVER_HOST_NAME=grom
      - SERVER_USE_IPV4=yes
      - SERVER_USE_IPV6=yes
      - SERVER_ALLOW_INTERFACES=eno1,docker0
      - WIDE_AREA_ENABLE_WIDE_AREA=yes
      - REFLECTOR_ENABLE_REFLECTOR=yes
  home-assistant:
    image: ghcr.io/home-assistant/home-assistant:2024.4.2
    container_name: home-assistant
    restart: unless-stopped
    volumes:
      - config:/config
      - /etc/localtime:/etc/localtime:ro
      - /run/dbus:/run/dbus:ro
    privileged: true
    network_mode: bridge
    labels:
      traefik.enable: true

      traefik.tcp.routers.home-assistant.entrypoints: homekit
      traefik.tcp.services.home-assistant.loadbalancer.server.port: 21063

      traefik.http.routers.home-assistant.tls: true
      traefik.http.routers.home-assistant.tls.certresolver: cloudflare
      traefik.http.routers.home-assistant.entrypoints: websecure
      traefik.http.routers.home-assistant.rule: Host(`home-assistant.local.alexisthe.best`)
      traefik.http.routers.home-assistant.service: home-assistant
      traefik.http.services.home-assistant.loadbalancer.server.port: 8123

volumes:
  config:
