services:
  home-assistant:
    image: ghcr.io/home-assistant/home-assistant:2024.4.2
    container_name: home-assistant
    restart: unless-stopped
    volumes:
      - config:/config
      - /etc/localtime:/etc/localtime:ro
      - /run/dbus:/run/dbus:ro
    privileged: true
    # networks:
    #   - traefik_default
    ports:
      - "8123:8123"

volumes:
  config:

networks:
  traefik_default:
    external: true
