services:
  home-assistant:
    image: ghcr.io/home-assistant/home-assistant:2024.8.0
    container_name: home-assistant
    restart: unless-stopped
    volumes:
      - config:/config
      - ./config/configuration.yaml:/config/configuration.yaml
      - /etc/localtime:/etc/localtime:ro
      - /run/dbus:/run/dbus
    privileged: true
    networks:
      - traefik_default
    labels:
      traefik.enable: true

      traefik.tcp.routers.home-assistant.entrypoints: homekit
      traefik.tcp.routers.home-assistant.rule: HostSNI(`*`)
      traefik.tcp.services.home-assistant.loadbalancer.server.port: 21063

      traefik.http.routers.home-assistant.tls.certresolver: cloudflare
      traefik.http.routers.home-assistant.entrypoints: websecure
      traefik.http.routers.home-assistant.rule: Host(`home-assistant.local.alexisthe.best`)
      traefik.http.services.home-assistant.loadbalancer.server.port: 8123

volumes:
  config:

networks:
  traefik_default:
    external: true
