services:
  cloudflared:
    container_name: cloudflared
    image: cloudflare/cloudflared:2024.4.0
    restart: unless-stopped
    command: tunnel --no-autoupdate run
    environment:
      - TUNNEL_TOKEN=$TUNNEL_TOKEN
    networks:
      - traefik

networks:
  traefik:
    external: true
