services:
  adguardhome:
    image: adguard/adguardhome:v0.107.48
    container_name: adguardhome
    restart: unless-stopped
    networks:
      - traefik_default
    volumes:
      - work:/opt/adguardhome/work
      - conf:/opt/adguardhome/conf
    labels:
      traefik.enable: true
      traefik.tcp.routers.adguardhome.tls: true
      traefik.tcp.routers.adguardhome.tls.certresolver: staging
      traefik.tcp.routers.adguardhome.entrypoints: dot
      traefik.tcp.routers.adguardhome.rule: Host(`adguardhome.local.alexisthe.best`)
      traefik.tcp.services.adguardhome.loadbalancer.server.port: 853

      traefik.http.routers.adguardhome.tls: true
      traefik.http.routers.adguardhome.tls.certresolver: staging
      traefik.http.routers.adguardhome.entrypoints: websecure
      traefik.http.routers.adguardhome.rule: Host(`adguardhome.local.alexisthe.best`)
      traefik.http.services.adguardhome.loadbalancer.server.port: 80
volumes:
  work:
  conf:

networks:
  traefik_default:
    external: true
