services:
  adguardhome:
    image: adguard/adguardhome:v0.107.48
    container_name: adguardhome
    restart: unless-stopped
    network_mode: bridge
    volumes:
      - work:/opt/adguardhome/work
      - conf:/opt/adguardhome/conf
    labels:
      traefik.enable: true

      traefik.tcp.routers.adguardhome.entrypoints: dnstcp
      traefik.tcp.routers.adguardhome.rule: HostSNI(`*`)
      traefik.tcp.services.adguardhome.loadbalancer.server.port: 53
      
      traefik.udp.routers.adguardhome.entrypoints: dnsudp
      traefik.udp.services.adguardhome.loadbalancer.server.port: 53

      traefik.http.routers.adguardhome.tls: true
      traefik.http.routers.adguardhome.tls.certresolver: cloudflare
      traefik.http.routers.adguardhome.entrypoints: websecure
      traefik.http.routers.adguardhome.rule: Host(`adguardhome.local.alexisthe.best`)
      traefik.http.services.adguardhome.loadbalancer.server.port: 80

volumes:
  work:
  conf:
