services:
  adguardhome:
    image: adguard/adguardhome:v0.107.48
    container_name: adguardhome
    restart: unless-stopped
    networks:
      - traefik_default
    volumes:
      - work:/opt/adguardhome/work
      - conf:/opt/adguardhome/conf
    ports:
      # DNS
      # - "53:53/tcp"
      # - "53:53/udp"

      # DNS-over-HTTPS / Dashboard
      - "81:80/tcp"
      # - "444:443/tcp"
      # - "444:443/udp"
      # - "3000:3000/tcp"

      # # DNS-over-TLS
      # - "853:853/tcp"
    labels:
      traefik.enable: true
      traefik.http.routers.adguardhome.entrypoints: dns
      traefik.http.routers.adguardhome.rule: Host(`adguardhome.alexisthe.best`)
      # traefik.http.routers.adguardhome.tls: true
      # traefik.http.routers.adguardhome.tls.certresolver: staging

volumes:
  work:
  conf:

networks:
  traefik_default:
    external: true
