services:
  adguardhome:
    image: adguard/adguardhome:v0.107.48
    container_name: adguardhome
    restart: unless-stopped
    networks:
      - traefik_default
    volumes:
      - work:/opt/adguardhome/work
      - conf:/opt/adguardhome/conf
    # ports:
    # DNS
    # - "53:53/tcp"
    # - "53:53/udp"

    # DNS-over-HTTPS / Dashboard
    # - "82:80/tcp"
    # - "444:443/tcp"
    # - "444:443/udp"
    # - "3000:3000/tcp"

    # # DNS-over-TLS
    # - "853:853/tcp"
    labels:
      traefik.enable: true
      traefik.udp.routers.adguardhome.entrypoints: dns
      traefik.udp.services.adguardhome.loadbalancer.server.port: 53

      traefik.http.routers.adguardhome.tls: true
      traefik.http.routers.adguardhome.tls.certresolver: staging
      traefik.http.routers.adguardhome.entrypoints: websecure
      traefik.http.routers.adguardhome.rule: Host(`adguardhome.local.alexisthe.best`)
      traefik.http.services.registry.loadbalancer.server.port: 80

      # - "traefik.http.routers.gitlab.rule=Host(`gitlab.example.com`)"
      # - "traefik.http.routers.gitlab.service=gitlab"
      # - "traefik.http.services.gitlab.loadbalancer.server.port=80"
      # - "traefik.http.routers.registry.rule=Host(`registry.gitlab.example.com`)"
      # - "traefik.http.routers.registry.service=registry"
      # - "traefik.http.services.registry.loadbalancer.server.port=5000"
volumes:
  work:
  conf:

networks:
  traefik_default:
    external: true
