services:
  adguardhome:
    image: adguard/adguardhome:v0.107.48
    container_name: adguardhome
    restart: unless-stopped
    volumes:
      - work:/opt/adguardhome/work
      - conf:/opt/adguardhome/conf
    ports:
      # DNS
      - "53:53/tcp"
      - "53:53/udp"

      # DNS-over-HTTPS / Dashboard
      - "80:80/tcp"
      - "443:443/tcp"
      - "443:443/udp"
      - "3000:3000/tcp"

      # DNS-over-TLS
      - "853:853/tcp"

volumes:
  work:
  conf:
