services:
  portainer:
    image: portainer/portainer-ce:2.19.4
    container_name: portainer
    restart: unless-stopped
    ports:
      - "8000:8000"
      - "9443:9443"
    labels:
      traefik.enable: true
      traefik.http.routers.portainer.tls: true
      traefik.http.routers.portainer.tls.certresolver: staging
      traefik.http.routers.portainer.entrypoints: websecure
      traefik.http.routers.portainer.rule: Host(`portainer.local.alexisthe.best`)
      traefik.http.services.portainer.loadbalancer.server.port: 9443
    networks:
      - traefik_default
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - data:/data

  portainer-agent:
    image: portainer/agent:2.19.4
    container_name: portainer-agent
    restart: unless-stopped
    ports:
      - "9001:9001"
    networks:
      - traefik_default
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker/volumes:/var/lib/docker/volumes
      - /:/host

volumes:
  data:

networks:
  traefik_default:
    external: true
