services:
  portainer:
    image: portainer/portainer-ce:2.19.4
    container_name: portainer
    restart: unless-stopped
    networks:
      - traefik_default
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - data:/data
    labels:
      traefik.enable: true
      traefik.http.routers.portainer.tls: true
      traefik.http.routers.portainer.tls.certresolver: cloudflare
      traefik.http.routers.portainer.entrypoints: websecure
      traefik.http.routers.portainer.rule: Host(`portainer.local.alexisthe.best`)
      traefik.http.routers.portainer.service: portainer
      traefik.http.services.portainer.loadbalancer.server.port: 9000

      traefik.http.routers.portainer-edge.tls: true
      traefik.http.routers.portainer-edge.tls.certresolver: cloudflare
      traefik.http.routers.portainer-edge.entrypoints: websecure
      traefik.http.routers.portainer-edge.rule: Host(`portainer-edge.local.alexisthe.best`)
      traefik.http.routers.portainer-edge.service: portainer-edge
      traefik.http.services.portainer-edge.loadbalancer.server.port: 8000

volumes:
  data:

networks:
  traefik_default:
    external: true
