---
- name: Setup Debian server for hosting
  hosts: all
  become: true
  vars:
    static_ip: 192.168.50.22
    netmask: 255.255.255.0
    gateway: 192.168.50.1
    raid_level: 5
    raid_device: /dev/md0
    raid_disks:
      - /dev/sdb
      - /dev/sdc
      - /dev/sdd
    mount_point: /mnt/terramaster
    filesystem: ext4
    user: alexmcdermott

  tasks:
    # Basics
    - name: Ensure passwordless sudo for user
      ansible.builtin.lineinfile:
        path: /etc/sudoers
        state: present
        line: "{{ user }} ALL=(ALL) NOPASSWD:ALL"
        validate: "visudo -cf %s"

    - name: Add user to users group
      ansible.builtin.user:
        name: "{{ user }}"
        groups: users
        append: yes

    # Static IP
    - name: Ensure static IP configuration for the active interface
      ansible.builtin.blockinfile:
        path: /etc/network/interfaces
        block: |
          auto {{ ansible_default_ipv4.interface }}
          iface {{ ansible_default_ipv4.interface }} inet static
            address {{ static_ip }}
            netmask {{ netmask }}
            gateway {{ gateway }}
        marker: "# {mark} MANAGED BY ANSIBLE"
        insertafter: "^auto {{ ansible_default_ipv4.interface }}$"
        state: present

      # Raid
    - name: Install required packages
      ansible.builtin.apt:
        name: mdadm
        state: present
        update_cache: yes

    - name: Check if RAID array exists
      ansible.builtin.command: mdadm --detail {{ raid_device }}
      register: raid_check
      ignore_errors: true
      changed_when: false

    - name: Create RAID array if it doesn't exist
      ansible.builtin.command: >
        mdadm --create --verbose {{ raid_device }}
        --level={{ raid_level }}
        --raid-devices={{ raid_disks | length }}
        {{ raid_disks | join(' ') }}
      when: raid_check.rc != 0
      register: raid_created

    - name: Create {{ filesystem }} filesystem on RAID array
      ansible.builtin.filesystem:
        fstype: "{{ filesystem }}"
        dev: "{{ raid_device }}"
      when: raid_created.changed

    - name: Create mount point
      ansible.builtin.file:
        path: "{{ mount_point }}"
        state: directory

    - name: Update mdadm configuration
      ansible.builtin.lineinfile:
        path: /etc/mdadm/mdadm.conf
        line: >
          ARRAY {{ raid_device }} 
          level={{ raid_level }} 
          num-devices={{ raid_disks | length }} 
          devices={{ raid_disks | join(',') }}
        state: present

    - name: Add entry to fstab for RAID
      ansible.builtin.lineinfile:
        path: /etc/fstab
        line: "{{ raid_device }} {{ mount_point }} {{ filesystem }} defaults,nofail 0 0"
        state: present

    - name: Set ownership and permissions on filesystem
      ansible.builtin.file:
        path: "{{ mount_point }}"
        owner: root
        group: users
        mode: "2775"
        recurse: yes
