services:
  dockge:
    image: louislam/dockge:1.4.2
    container_name: dockge
    restart: unless-stopped
    networks:
      - traefik_default
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /home/alexmcdermott/homelab:/opt/stacks
      - data:/app/data
    labels:
      traefik.enable: true
      traefik.http.routers.dockge.tls.certresolver: cloudflare
      traefik.http.routers.dockge.entrypoints: websecure
      traefik.http.routers.dockge.rule: Host(`dockge.local.alexisthe.best`)
      traefik.http.services.dockge.loadbalancer.server.port: 5001

volumes:
  data:

networks:
  traefik_default:
    external: true